### ISSUE TITLE
Limited access to the dashboard

### ISSUE THREAD

**Issue by kart-able** [yhirano55/active_admin_role#10]
May I point to your installation procedure first ? 
`rails generate active_admin:install` should read `rails generate active_admin_role:install`

It seems your app checks for installed files and finds a missing one:
`The file [path_to]/app/admin/admin_user.rb does not appear to exist` (in the console)
Actually, there has been a file named admin_user**s**.rb installed.

When I log in as an admin, I just have access to the dashboard. All the tabs Users or Posts, etc are no longer active. As you understand, I have a users model in addition to the admin_users and this may cause a problem?

I have checked all the files in your sample application. Mine are just the same.

**Comment by yhirano55** [comment]
Have you executed `bin/rails db:seed` ?

**Comment by kart-able** [comment]
Actually, I haven't. Account admin@example.com has already been created from my original installation of active admin.

**Comment by yhirano55** [comment]
> May I point to your installation procedure first ?
> rails generate active_admin:install should read rails generate active_admin_role:install
> 
> It seems your app checks for installed files and finds a missing one:
> The file [path_to]/app/admin/admin_user.rb does not appear to exist (in the console)
> Actually, there has been a file named admin_users.rb installed.

Seems the bug of this gem's generator.

**Comment by yhirano55** [comment]
Probably, you should change `admin@example.com` user's role:

```
$ bin/rails c

user = AdminUser.find_by!(email: "admin@example.com")
user.update!(role: :admin)
```

**Comment by kart-able** [comment]
That was it! Now I intend to play with the configuration and I will probably open a discussion on Stackoverflow about it. 

A last thing here: the edition of roles through the 'batch action' button does not work. For the time being, I only have the option 'delete', even after adding a few AdminUsers.

**Comment by yhirano55** [comment]
@kart-able I'm looking forward to receive pull request from you. This is Open Source Software, OK?
