### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by yhirano55** [yhirano55/active_admin_role#19]
I'm looking for maintainer of active_admin_role gem. Currently I don't use ActiveAdmin in any my projects, so I don't have motivations to maintain plugins any more. Please someone help me.

I'm ready to grant someone as maintainer and transfer gem management right to someone.

**Comment by yhirano55** [comment]
@alexey or @kart-able Hi, do you have any motivation which maintains this gem? If you have, I'll grant maintainer rights to you.

**Comment by luilver** [comment]
Hi @yhirano55, I'm currently improving some [branch of FFaker](https://github.com/ffaker/ffaker/commit/f6b5f7a60a84ed9d08b181387375b8ea4455a229) but if you don't have a better candidate and you don't mind ... I'll do ! I wouldn't hesitate receiving a technical minimum of how to maintain the gem. Best regards!

**Comment by yhirano55** [comment]
@luilver Thank you for your proposal. I invited you this repo

**Comment by varyonic** [comment]
Consider transferring to (or joining) https://github.com/activeadmin-plugins

**Comment by yhirano55** [comment]
@varyonic Thanks for the advise.

@Fivell Excuse me. Could I transfer this activeadmin's plugin to activeadmin-plugins org? Currently, I don't use ActiveAdmin well. So I don't have any motivation to maintain this gem. But this gem is used by some developers, and I want to resolve this problem.

**Comment by Fivell** [comment]
@yhirano55 sure, lets transfer

**Comment by yhirano55** [comment]
@Fivell Thank you so much. I’ll do now.

**Comment by yhirano55** [comment]
@Fivell I couldn’t transfer this repo to activeadmin-plugins, because I don’t have a permission to create repos in activeadmin-plugins. Would you give me a permission to create repos in activeadmin-plugins?

**Comment by Fivell** [comment]
@yhirano55 I sent you invite to organization

**Comment by yhirano55** [comment]
@Fivell Thanks! I’ve transferred.

**Comment by varyonic** [comment]
Would you like to transfer the sample also?

**Comment by yhirano55** [comment]
@varyonic Yes, I want to do.
