### ISSUE TITLE
trouble adding admin users from inside the app

### ISSUE THREAD

**Issue by quietwar** [yhirano55/active_admin_role#9]
Hello, I have installed your gem and I have created admin roles by seeding the database, however, I am having trouble creating users from the active_admin menu now. How you encounter this issue? Or is this just something i am not doing in my code?

**Comment by yhirano55** [comment]
Hi, I didn't know what you want to do 🤔 What's your expectations for this gem.

[This is sample application](https://github.com/yhirano55-playground/active_admin_role_sample/). And currently, this gem's generator includes some bugs (`role_changeable` is not inserted into `admin/admin_users.rb` )
